service_project    = "your-service-project-id"
host_project       = "your-host-project-id"
region             = "your-region"
shared_subnet_name = "your-subnet-name"
sa_email           = "your-service-account-email"
